### ISSUE TITLE
初始化监听showPickerModel的逻辑需要优化

### ISSUE THREAD

**Issue by gengchen528** [J1ong/vuejs-mobile-datepicker#1]
如图，如果设置的```endDate```和```defaultDate```都是```new Date()```的话，这里的初始化无法成功，因为组件初始化也是要一定时间的，最后就是导致```this.defaultDate <= this.endDate```一直为false
![image](https://user-images.githubusercontent.com/20028566/66750910-4f1ddf00-eec0-11e9-8501-3e64125769ff.png)

**Comment by J1ong** [comment]
> 那么，如果设置的`endDate`和`defaultDate`都是`new Date()`的话，这里的初始化无法成功，因为组件初始化也是要一定时间的，最后就是导致`this.defaultDate <= this.endDate`一直为false
> ![图片](https://user-images.githubusercontent.com/20028566/66750910-4f1ddf00-eec0-11e9-8501-3e64125769ff.png)

你好，首先非常感谢大佬你提出的宝贵意见。针对你的意见，我对在defaultDate和endDate都为new Date()的情况下进行了测试，并额外对startDate、defaultDate和endDate都为new Date()进行了测试，发现组件初始化都是成功的。对此我是这样理解的，defaultDate和endDate初始化数据都是new Date()的话，那么，它们的值在父组件向子组件传递数据时就已经初始化好了，不会再变了·，并且它们的值也是相等的。

**Comment by gengchen528** [comment]
可能我叙述的有点问题，是在组件调用的时候，传值出现这个问题的。 我log后发现存在20ms左右的差值导致
![image](https://user-images.githubusercontent.com/20028566/66797832-a793c180-ef3e-11e9-8e0b-db3aecbf0ea9.png)

**Comment by J1ong** [comment]
你endDate赋值前是否执行其它操作呢？从而导致20ms左右的差值。如果你的endDate赋值和currentDate赋值相同的话，建议endDate=currentDate；
