### ISSUE TITLE
苹果手机通过点击按钮无法打开日期弹出层

### ISSUE THREAD

**Issue by songjianet** [J1ong/vuejs-mobile-datepicker#4]

**Comment by J1ong** [comment]
关于在 iOS 上无法渲染组件的问题，请确认在创建 Date 对象时没有使用new Date('2020-01-01')这样的写法，iOS 不支持以中划线分隔的日期格式，正确写法是new Date('2020/01/01')。

**Comment by songjianet** [comment]
嗯嗯，我在通过对你的源码进行调试时候发现这个问题了，多谢
